name: devbuild

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: devbuild-${{ github.event.pull_request.number || github.ref }}${{ github.event.label.name && github.event.label.name != 'skip-ci' && '-otherlabel' || '' }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  check_skip:
    uses: ./.github/workflows/check_skip_ci.yml
    permissions:
      contents: read
      pull-requests: read
      issues: read

  build:

    needs: [check_skip]

    if: |
      needs.check_skip.outputs.skip != 'true' &&
      github.event_name == 'pull_request'

    name: build_${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-24.04]

      fail-fast: false

    steps:

      - name: fail like a broken build
        run: exit 1

  plain:

    needs: [check_skip]

    if: |
      needs.check_skip.outputs.skip != 'true' &&
      github.event_name == 'pull_request'

    runs-on: ubuntu-24.04

    timeout-minutes: 5

    steps:

      - name: fail like a broken build without a matrix
        run: exit 1
